version: 1.0.0-alpha-{build}
image: Visual Studio 2017
configuration: Release
init:
    - cmd: git config --global core.autocrlf true
dotnet_csproj:
  patch:  true
  file: '**\*.csproj'
  version:  '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe

before_build:
- cmd: >-
    dotnet --version

    dotnet restore ./src/IdentityServer4.Contrib.LiteDB.sln --verbosity m
build:
  project: ./src/IdentityServer4.Contrib.LiteDB.sln
  verbosity: minimal
after_build:
- cmd: dotnet pack /p:PackageVersion=%appveyor_build_version% ./src/IdentityServer4.Contrib.LiteDB.sln
artifacts:
- path: '**\IdentityServer4.*.nupkg'
  name: IdentityServer4.Contrib.LiteDB
  
deploy:
- provider: NuGet
  api_key:
    secure: B/f51VFX8VlPydPBC8o0fhaoDnDY/nFwXF8rWtCaGSbjTs3iWh7nY6geUynibgJs
